### ISSUE TITLE
use "import" or "require("survey-react-bootstrap") not work!

### ISSUE THREAD

**Issue by cyberiuscorp** [andrewtelnov/surveyjs#52] opened 2016-08-18 07:45 UTC
Is there any chance you add  this?
this is error # 
node_modules/survey-react-bootstrap/dist/survey.react.bootstrap.js:4519
}(React.Component));

THANKS

**Comment by andrewtelnov** [comment] 2016-08-21 16:51
Hi, I do not mind to support it. Could you please point me a direction?

**Comment by cpruijsen** [comment] 2016-09-30 09:49
@andrewtelnov duplicate of https://github.com/andrewtelnov/surveyjs/issues/75

**Comment by andrewtelnov** [comment] 2016-10-11 08:18
@cyberiuscorp @cpruijsen 
Guys, I have updated https://github.com/andrewtelnov/surveyjs/issues/75.
There is a version that should works fine now. It uses webpack. Could you [check it out](https://github.com/dmitrykurmanov/surveyjs)? 

Thank you,
Andrew

**Closed** 2016-10-30 09:44 UTC
